repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: double-quote-string-fixer

  - repo: https://github.com/psf/black
    rev: "23.9.1"
    hooks:
      - id: black
